/**
 * OFFICIAL 195 RECOGNIZED COUNTRIES OF THE WORLD
 * According to the Worldometer Geography Guide (193 UN Member States + 2 Observer States)
 * Flag images loaded from: https://flagcdn.com/w80/{code}.png
 * Includes audienceWeight for YouTube Live Stream audience retention optimization
 */

const COUNTRIES = [
  { name: "Afghanistan", code: "af", weight: 1.0 }, 
  { name: "Albania", code: "al", weight: 1.0 }, 
  { name: "Algeria", code: "dz", weight: 2.0 }, 
  { name: "Andorra", code: "ad", weight: 1.0 }, 
  { name: "Angola", code: "ao", weight: 1.0 }, 
  { name: "Antigua and Barbuda", code: "ag", weight: 1.0 }, 
  { name: "Argentina", code: "ar", weight: 3.5 }, 
  { name: "Armenia", code: "am", weight: 1.0 }, 
  { name: "Australia", code: "au", weight: 2.0 }, 
  { name: "Austria", code: "at", weight: 1.0 }, 
  { name: "Azerbaijan", code: "az", weight: 1.0 }, 
  { name: "Bahamas", code: "bs", weight: 1.0 }, 
  { name: "Bahrain", code: "bh", weight: 1.0 }, 
  { name: "Bangladesh", code: "bd", weight: 3.5 }, 
  { name: "Barbados", code: "bb", weight: 1.0 }, 
  { name: "Belarus", code: "by", weight: 1.0 }, 
  { name: "Belgium", code: "be", weight: 1.0 }, 
  { name: "Belize", code: "bz", weight: 1.0 }, 
  { name: "Benin", code: "bj", weight: 1.0 }, 
  { name: "Bhutan", code: "bt", weight: 1.0 }, 
  { name: "Bolivia", code: "bo", weight: 1.0 }, 
  { name: "Bosnia and Herzegovina", code: "ba", weight: 1.0 }, 
  { name: "Botswana", code: "bw", weight: 1.0 }, 
  { name: "Brazil", code: "br", weight: 3.5 }, 
  { name: "Brunei", code: "bn", weight: 1.0 }, 
  { name: "Bulgaria", code: "bg", weight: 1.0 }, 
  { name: "Burkina Faso", code: "bf", weight: 1.0 }, 
  { name: "Burundi", code: "bi", weight: 1.0 }, 
  { name: "Cabo Verde", code: "cv", weight: 1.0 }, 
  { name: "Cambodia", code: "kh", weight: 1.0 }, 
  { name: "Cameroon", code: "cm", weight: 1.0 }, 
  { name: "Canada", code: "ca", weight: 2.0 }, 
  { name: "Central African Republic", code: "cf", weight: 1.0 }, 
  { name: "Chad", code: "td", weight: 1.0 }, 
  { name: "Chile", code: "cl", weight: 1.0 }, 
  { name: "China", code: "cn", weight: 1.0 }, 
  { name: "Colombia", code: "co", weight: 2.0 }, 
  { name: "Comoros", code: "km", weight: 1.0 }, 
  { name: "Congo", code: "cg", weight: 1.0 }, 
  { name: "Costa Rica", code: "cr", weight: 1.0 }, 
  { name: "Croatia", code: "hr", weight: 1.0 }, 
  { name: "Cuba", code: "cu", weight: 1.0 }, 
  { name: "Cyprus", code: "cy", weight: 1.0 }, 
  { name: "Czech Republic (Czechia)", code: "cz", weight: 1.0 }, 
  { name: "C\u00f4te d'Ivoire", code: "ci", weight: 1.0 }, 
  { name: "DR Congo", code: "cd", weight: 1.0 }, 
  { name: "Denmark", code: "dk", weight: 1.0 }, 
  { name: "Djibouti", code: "dj", weight: 1.0 }, 
  { name: "Dominica", code: "dm", weight: 1.0 }, 
  { name: "Dominican Republic", code: "do", weight: 1.0 }, 
  { name: "Ecuador", code: "ec", weight: 1.0 }, 
  { name: "Egypt", code: "eg", weight: 3.5 }, 
  { name: "El Salvador", code: "sv", weight: 1.0 }, 
  { name: "Equatorial Guinea", code: "gq", weight: 1.0 }, 
  { name: "Eritrea", code: "er", weight: 1.0 }, 
  { name: "Estonia", code: "ee", weight: 1.0 }, 
  { name: "Eswatini", code: "sz", weight: 1.0 }, 
  { name: "Ethiopia", code: "et", weight: 1.0 }, 
  { name: "Fiji", code: "fj", weight: 1.0 }, 
  { name: "Finland", code: "fi", weight: 1.0 }, 
  { name: "France", code: "fr", weight: 3.5 }, 
  { name: "Gabon", code: "ga", weight: 1.0 }, 
  { name: "Gambia", code: "gm", weight: 1.0 }, 
  { name: "Georgia", code: "ge", weight: 1.0 }, 
  { name: "Germany", code: "de", weight: 3.5 }, 
  { name: "Ghana", code: "gh", weight: 2.0 }, 
  { name: "Greece", code: "gr", weight: 1.0 }, 
  { name: "Grenada", code: "gd", weight: 1.0 }, 
  { name: "Guatemala", code: "gt", weight: 1.0 }, 
  { name: "Guinea", code: "gn", weight: 1.0 }, 
  { name: "Guinea-Bissau", code: "gw", weight: 1.0 }, 
  { name: "Guyana", code: "gy", weight: 1.0 }, 
  { name: "Haiti", code: "ht", weight: 1.0 }, 
  { name: "Holy See", code: "va", weight: 1.0 }, 
  { name: "Honduras", code: "hn", weight: 1.0 }, 
  { name: "Hungary", code: "hu", weight: 1.0 }, 
  { name: "Iceland", code: "is", weight: 1.0 }, 
  { name: "India", code: "in", weight: 3.5 }, 
  { name: "Indonesia", code: "id", weight: 3.5 }, 
  { name: "Iran", code: "ir", weight: 1.0 }, 
  { name: "Iraq", code: "iq", weight: 2.0 }, 
  { name: "Ireland", code: "ie", weight: 1.0 }, 
  { name: "Israel", code: "il", weight: 1.0 }, 
  { name: "Italy", code: "it", weight: 2.0 }, 
  { name: "Jamaica", code: "jm", weight: 1.0 }, 
  { name: "Japan", code: "jp", weight: 3.5 }, 
  { name: "Jordan", code: "jo", weight: 1.0 }, 
  { name: "Kazakhstan", code: "kz", weight: 1.0 }, 
  { name: "Kenya", code: "ke", weight: 2.0 }, 
  { name: "Kiribati", code: "ki", weight: 1.0 }, 
  { name: "Kuwait", code: "kw", weight: 1.0 }, 
  { name: "Kyrgyzstan", code: "kg", weight: 1.0 }, 
  { name: "Laos", code: "la", weight: 1.0 }, 
  { name: "Latvia", code: "lv", weight: 1.0 }, 
  { name: "Lebanon", code: "lb", weight: 1.0 }, 
  { name: "Lesotho", code: "ls", weight: 1.0 }, 
  { name: "Liberia", code: "lr", weight: 1.0 }, 
  { name: "Libya", code: "ly", weight: 1.0 }, 
  { name: "Liechtenstein", code: "li", weight: 1.0 }, 
  { name: "Lithuania", code: "lt", weight: 1.0 }, 
  { name: "Luxembourg", code: "lu", weight: 1.0 }, 
  { name: "Madagascar", code: "mg", weight: 1.0 }, 
  { name: "Malawi", code: "mw", weight: 1.0 }, 
  { name: "Malaysia", code: "my", weight: 2.0 }, 
  { name: "Maldives", code: "mv", weight: 1.0 }, 
  { name: "Mali", code: "ml", weight: 1.0 }, 
  { name: "Malta", code: "mt", weight: 1.0 }, 
  { name: "Marshall Islands", code: "mh", weight: 1.0 }, 
  { name: "Mauritania", code: "mr", weight: 1.0 }, 
  { name: "Mauritius", code: "mu", weight: 1.0 }, 
  { name: "Mexico", code: "mx", weight: 3.5 }, 
  { name: "Micronesia", code: "fm", weight: 1.0 }, 
  { name: "Moldova", code: "md", weight: 1.0 }, 
  { name: "Monaco", code: "mc", weight: 1.0 }, 
  { name: "Mongolia", code: "mn", weight: 1.0 }, 
  { name: "Montenegro", code: "me", weight: 1.0 }, 
  { name: "Morocco", code: "ma", weight: 2.0 }, 
  { name: "Mozambique", code: "mz", weight: 1.0 }, 
  { name: "Myanmar", code: "mm", weight: 1.0 }, 
  { name: "Namibia", code: "na", weight: 1.0 }, 
  { name: "Nauru", code: "nr", weight: 1.0 }, 
  { name: "Nepal", code: "np", weight: 1.0 }, 
  { name: "Netherlands", code: "nl", weight: 2.0 }, 
  { name: "New Zealand", code: "nz", weight: 1.0 }, 
  { name: "Nicaragua", code: "ni", weight: 1.0 }, 
  { name: "Niger", code: "ne", weight: 1.0 }, 
  { name: "Nigeria", code: "ng", weight: 3.5 }, 
  { name: "North Korea", code: "kp", weight: 1.0 }, 
  { name: "North Macedonia", code: "mk", weight: 1.0 }, 
  { name: "Norway", code: "no", weight: 1.0 }, 
  { name: "Oman", code: "om", weight: 1.0 }, 
  { name: "Pakistan", code: "pk", weight: 3.5 }, 
  { name: "Palau", code: "pw", weight: 1.0 }, 
  { name: "Panama", code: "pa", weight: 1.0 }, 
  { name: "Papua New Guinea", code: "pg", weight: 1.0 }, 
  { name: "Paraguay", code: "py", weight: 1.0 }, 
  { name: "Peru", code: "pe", weight: 2.0 }, 
  { name: "Philippines", code: "ph", weight: 3.5 }, 
  { name: "Poland", code: "pl", weight: 2.0 }, 
  { name: "Portugal", code: "pt", weight: 1.0 }, 
  { name: "Qatar", code: "qa", weight: 1.0 }, 
  { name: "Romania", code: "ro", weight: 1.0 }, 
  { name: "Russia", code: "ru", weight: 1.0 }, 
  { name: "Rwanda", code: "rw", weight: 1.0 }, 
  { name: "Saint Kitts & Nevis", code: "kn", weight: 1.0 }, 
  { name: "Saint Lucia", code: "lc", weight: 1.0 }, 
  { name: "Samoa", code: "ws", weight: 1.0 }, 
  { name: "San Marino", code: "sm", weight: 1.0 }, 
  { name: "Sao Tome & Principe", code: "st", weight: 1.0 }, 
  { name: "Saudi Arabia", code: "sa", weight: 2.0 }, 
  { name: "Senegal", code: "sn", weight: 1.0 }, 
  { name: "Serbia", code: "rs", weight: 1.0 }, 
  { name: "Seychelles", code: "sc", weight: 1.0 }, 
  { name: "Sierra Leone", code: "sl", weight: 1.0 }, 
  { name: "Singapore", code: "sg", weight: 1.0 }, 
  { name: "Slovakia", code: "sk", weight: 1.0 }, 
  { name: "Slovenia", code: "si", weight: 1.0 }, 
  { name: "Solomon Islands", code: "sb", weight: 1.0 }, 
  { name: "Somalia", code: "so", weight: 1.0 }, 
  { name: "South Africa", code: "za", weight: 2.0 }, 
  { name: "South Korea", code: "kr", weight: 2.0 }, 
  { name: "South Sudan", code: "ss", weight: 1.0 }, 
  { name: "Spain", code: "es", weight: 2.0 }, 
  { name: "Sri Lanka", code: "lk", weight: 1.0 }, 
  { name: "St. Vincent & Grenadines", code: "vc", weight: 1.0 }, 
  { name: "State of Palestine", code: "ps", weight: 1.0 }, 
  { name: "Sudan", code: "sd", weight: 1.0 }, 
  { name: "Suriname", code: "sr", weight: 1.0 }, 
  { name: "Sweden", code: "se", weight: 1.0 }, 
  { name: "Switzerland", code: "ch", weight: 1.0 }, 
  { name: "Syria", code: "sy", weight: 1.0 }, 
  { name: "Tajikistan", code: "tj", weight: 1.0 }, 
  { name: "Tanzania", code: "tz", weight: 1.0 }, 
  { name: "Thailand", code: "th", weight: 2.0 }, 
  { name: "Timor-Leste", code: "tl", weight: 1.0 }, 
  { name: "Togo", code: "tg", weight: 1.0 }, 
  { name: "Tonga", code: "to", weight: 1.0 }, 
  { name: "Trinidad and Tobago", code: "tt", weight: 1.0 }, 
  { name: "Tunisia", code: "tn", weight: 1.0 }, 
  { name: "Turkey", code: "tr", weight: 3.5 }, 
  { name: "Turkmenistan", code: "tm", weight: 1.0 }, 
  { name: "Tuvalu", code: "tv", weight: 1.0 }, 
  { name: "Uganda", code: "ug", weight: 1.0 }, 
  { name: "Ukraine", code: "ua", weight: 2.0 }, 
  { name: "United Arab Emirates", code: "ae", weight: 1.0 }, 
  { name: "United Kingdom", code: "gb", weight: 3.5 }, 
  { name: "United States", code: "us", weight: 3.5 }, 
  { name: "Uruguay", code: "uy", weight: 1.0 }, 
  { name: "Uzbekistan", code: "uz", weight: 1.0 }, 
  { name: "Vanuatu", code: "vu", weight: 1.0 }, 
  { name: "Venezuela", code: "ve", weight: 1.0 }, 
  { name: "Vietnam", code: "vn", weight: 3.5 }, 
  { name: "Yemen", code: "ye", weight: 1.0 }, 
  { name: "Zambia", code: "zm", weight: 1.0 }, 
  { name: "Zimbabwe", code: "zw", weight: 1.0 }, 
];

// Get flag image URL for a country code (uses high-definition local vector SVGs)
function getFlagUrl(code, size = 80) {
  if (!code) return '';
  return `/flags/${String(code).toLowerCase()}.svg`;
}

if (typeof module !== 'undefined') {
  COUNTRIES.getFlagUrl = getFlagUrl;
  module.exports = COUNTRIES;
}
